/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("delta.java-application-conventions")
}

dependencies {
    implementation("io.javalin:javalin")
    implementation("com.fasterxml.jackson.core:jackson-databind")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")

    runtimeOnly("org.slf4j:slf4j-simple")
}

application {
    // Define the main class for the application.
    mainClass.set("delta.app.App")
}

tasks.jar {
    dependsOn(configurations.runtimeClasspath)

    from(project.layout.projectDirectory.file("../LICENSE")) {
        into("META-INF")
    }
    from(configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }) {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }

    manifest {
        attributes("Main-Class" to "delta.app.App")
    }
}

tasks.distTar { enabled = false }
